import Header from "./components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-montserrat",
});

const kharkivTone = localFont({
  src: [
    {
      path: "../../public/fonts/KharkivTone-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-kharkiv-tone",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk">
      <body
        className={`${montserrat.variable} ${kharkivTone.variable} font-sans antialiased`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
